language: java
jdk:
  - openjdk8

sudo: true
addons:
  chrome: stable
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - '$HOME/.npm'
    - '$HOME/packages/*/.npm'
    - '$HOME/packages/*/.cache'
    - '$HOME/.gradle/caches/'
    - '$HOME/.gradle/wrapper/'
env:
  global:
    - NODE_VERSION=8.16.0
  matrix:
    - PACKAGE=navi-app
    - PACKAGE=navi-core
    - PACKAGE=navi-dashboards
    - PACKAGE=navi-data
    - PACKAGE=navi-directory
    - PACKAGE=navi-reports
    - PACKAGE=navi-webservice
branches:
  only:
    - master
matrix:
  fast_finish: true
before_install:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    openssl aes-256-cbc -K $encrypted_3709885499a2_key -iv $encrypted_3709885499a2_iv -in travis-secrets.tar.gz.enc -out travis-secrets.tar.gz -d;
    echo "Successfully decrypted travis secrets";
    tar xvf travis-secrets.tar.gz;
    fi
install:
  - if [[ "${PACKAGE}" == "navi-webservice" ]]; then
    pushd packages/webservice && ./gradlew assemble && popd;
    else
    nvm install ${NODE_VERSION};
    npm config set spin false;
    travis_wait npm ci;
    npx lerna exec --scope ${PACKAGE} -- bower install || true;
    fi
script:
  - if [[ "${PACKAGE}" == "navi-webservice" ]]; then
    pushd packages/webservice && ./gradlew check && popd;
    else
    travis_wait npx lerna run test --scope ${PACKAGE};
    fi
jobs:
  include:
    - stage: Publish
      if: branch = master AND repo = yahoo/navi AND type = push
      node_js: '8'
      script: bash ./scripts/ci-publish.sh
