language: java
jdk:
  - openjdk8

git:
  depth: false
addons:
  chrome: stable
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - '$HOME/.npm'
    - '$HOME/packages/*/.npm'
    - '$HOME/packages/*/.cache'
    - '$HOME/.gradle/caches/'
    - '$HOME/.gradle/wrapper/'
env:
  global:
    - NODE_VERSION=8.16.0
  matrix:
    - PACKAGE=navi-app
    - PACKAGE=navi-core
    - PACKAGE=navi-dashboards
    - PACKAGE=navi-data
    - PACKAGE=navi-directory
    - PACKAGE=navi-notifications
    - PACKAGE=navi-reports
    - PACKAGE=navi-search
    - PACKAGE=navi-webservice
branches:
  only:
    - master
install:
  - if [[ "${PACKAGE}" == "navi-webservice" ]]; then
    pushd packages/webservice && ./gradlew assemble && popd;
    else
    nvm install ${NODE_VERSION};
    npm config set spin false;
    npm ci;
    fi
script:
  - if [[ "${PACKAGE}" == "navi-webservice" ]]; then
    pushd packages/webservice && ./gradlew check && popd;
    else
    npx lerna run test --scope ${PACKAGE} --stream;
    fi
jobs:
  fast_finish: true
  include:
    - stage: 'Publish'
      if: branch = master AND repo = yahoo/navi AND type = push
      node_js: '8'
      name: 'NPM'
      script: bash ./scripts/npm-publish.sh
    - script: bash ./scripts/gh-pages-publish.sh
      name: 'GitHub Pages'
      node_js: '8'
      if: branch = master AND repo = yahoo/navi AND type = push
    - script: bash ./scripts/artifactory-publish.sh
      name: 'Artifactory'
      node_js: '8'
      if: branch = master AND repo = yahoo/navi AND type = push
